name: fsnotify
version: '0.3.0.1'
synopsis: Cross platform library for file change notification.
description: ! 'Cross platform library for file creation, modification,

  and deletion notification. This library builds upon

  existing libraries for platform-specific Windows, Mac,

  and Linux filesystem event notification.'
category: Filesystem
author:
- Mark Dittmer <mark.s.dittmer@gmail.com>
- Niklas Broberg
maintainer: Tom McLaughlin <tom@codedown.io>
license: BSD3
homepage: https://github.com/haskell-fswatch/hfsnotify
git: git://github.com/haskell-fswatch/hfsnotify
extra-source-files:
- README.md
- CHANGELOG.md
- test/Test.hs
- test/EventUtils.hs
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - System.FSNotify
  - System.FSNotify.Devel
  dependencies:
  - base >=4.8 && <5
  - bytestring >=0.10.2
  - containers >=0.4
  - directory >=1.2.7.0
  - filepath >=1.3.0.0
  - text >=0.11.0
  - time >=1.1
  - async >=2.0.1
  - unix-compat >=0.2
  when:
  - condition: os(linux)
    then:
      cpp-options: -DOS_Linux
      dependencies:
      - hinotify >=0.3.0
      - shelly >=1.6.5
      - unix >=2.7.1.0
    else:
      when:
      - condition: os(windows)
        then:
          source-dirs: win-src
          cpp-options: -DOS_Win32
          dependencies:
          - Win32
        else:
          when:
          - condition: os(osx)
            cpp-options: -DOS_Mac
            dependencies:
            - hfsevents >=0.1.3
tests:
  test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    when:
    - condition: os(windows)
      then:
        dependencies:
        - base >=4.3.1.0
        - tasty >=0.5
        - tasty-hunit
        - directory
        - filepath
        - unix-compat
        - fsnotify
        - async >=2
        - temporary
        - random
        - Win32
      else:
        dependencies:
        - base >=4.3.1.0
        - tasty >=0.5
        - tasty-hunit
        - directory
        - filepath
        - unix-compat
        - fsnotify
        - async >=2
        - temporary
        - random
