name:                fsnotify
version:             0.4.0.0
license:             BSD3
license-file:        LICENSE
author:              Mark Dittmer <mark.s.dittmer@gmail.com>, Niklas Broberg
maintainer:          Tom McLaughlin <tom@codedown.io>
category:            Filesystem
homepage:            https://github.com/haskell-fswatch/hfsnotify
synopsis:            Cross platform library for file change notification.
description:         Cross platform library for file creation, modification, and deletion notification. This library builds upon existing libraries for platform-specific Windows, Mac, and Linux filesystem event notification.

extra-source-files:
- README.md
- CHANGELOG.md
- test/Main.hs

when:
- condition: os(linux)
  cpp-options: -DOS_Linux
- condition: os(windows)
  cpp-options: -DOS_Windows
- condition: os(darwin)
  cpp-options: -DOS_Mac

library:
  source-dirs: src

  other-modules:
  - System.FSNotify.Find
  - System.FSNotify.Listener
  - System.FSNotify.Path
  - System.FSNotify.Polling
  - System.FSNotify.Types

  when:
  - condition: os(linux)
    other-modules:
    - System.FSNotify.Linux
    dependencies:
    - hinotify >= 0.3.7
    - unix >= 2.7.1.0

  - condition: os(windows)
    source-dirs: win-src
    other-modules:
    - System.FSNotify.Win32
    - System.Win32.FileNotify
    - System.Win32.Notify
    dependencies: Win32

  - condition: os(darwin)
    other-modules:
    - System.FSNotify.OSX
    dependencies: hfsevents >= 0.1.3

  dependencies:
  - base >= 4.8 && < 5
  - async >= 2.0.0.0
  - bytestring >= 0.10.2
  - containers >= 0.4
  - directory >= 1.3.0.0
  - filepath >= 1.3.0.0
  - monad-control >= 1.0.0.0
  - safe-exceptions >= 0.1.0.0
  - text >= 0.11.0
  - time >= 1.1
  - unix-compat >= 0.2
  ghc-options:
  - -Wall
  exposed-modules:
    - System.FSNotify
    - System.FSNotify.Devel


executables:
  tests:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -Wall
    dependencies:
    - base >= 4.3.1.0
    - exceptions
    - sandwich
    - directory
    - filepath
    - unix-compat
    - fsnotify
    - async >= 2
    - safe-exceptions
    - temporary
    - unliftio
    - random
    - retry
    when:
    - condition: os(windows)
      dependencies: Win32
